{"id"=>"4ed642c49adf509595e7c2d6",
 "createdAt"=>1322664644,
 "text"=>
  "Had a great lunch at Zinc yesterday.  It was very easy to eat out, maintain my paleo and ViSalus diet.  Awesome.",
 "likes"=>{"count"=>0, "groups"=>[]},
 "todo"=>{"count"=>0},
 "done"=>{"count"=>1},
 "venue"=>
  {"id"=>"4b60ce7cf964a520b5fa29e3",
   "name"=>"Zinc Cafe",
   "contact"=>{"phone"=>"6099539462", "formattedPhone"=>"(609) 953-9462"},
   "location"=>
    {"address"=>"679 Stokes Road",
     "lat"=>39.868746399879456,
     "lng"=>-74.80938991,
     "distance"=>30772,
     "postalCode"=>"08055",
     "city"=>"Medford",
     "state"=>"New Jersey",
     "country"=>"United States",
     "cc"=>"US"},
   "categories"=>
    [{"id"=>"4bf58dd8d48988d14e941735",
      "name"=>"American Restaurant",
      "pluralName"=>"American Restaurants",
      "shortName"=>"American",
      "icon"=>"https://foursquare.com/img/categories/food/default.png",
      "parents"=>["Food"],
      "primary"=>true}],
   "verified"=>false,
   "stats"=>{"checkinsCount"=>213, "usersCount"=>90, "tipCount"=>6},
   "likes"=>
    {"count"=>1,
     "groups"=>
      [{"type"=>"others",
        "count"=>1,
        "items"=>
         [{"id"=>"24613153",
           "firstName"=>"Daryl",
           "lastName"=>"A.",
           "photo"=>"https://is1.4sqi.net/userpix_thumbs/2JNW2T1SFC3KIMS0.jpg",
           "tips"=>{"count"=>0},
           "lists"=>{"groups"=>[{"type"=>"created", "count"=>1, "items"=>[]}]},
           "gender"=>"female",
           "homeCity"=>"Medford, NJ",
           "bio"=>"",
           "contact"=>{"facebook"=>"1557516492"}}]}],
     "summary"=>"1 like"}},
 "user"=>
  {"id"=>"7493027",
   "firstName"=>"Darla",
   "lastName"=>"K.",
   "photo"=>"https://is0.4sqi.net/userpix_thumbs/J0CIZ44N532OMBHB.jpg",
   "tips"=>{"count"=>14},
   "lists"=>{"groups"=>[{"type"=>"created", "count"=>1, "items"=>[]}]},
   "gender"=>"female",
   "homeCity"=>"Medford, NJ",
   "bio"=>"",
   "contact"=>{"twitter"=>"darlaklausner", "facebook"=>"1441863873"}}}

