defaults: &defaults
  host: localhost
  persist_in_safe_mode: true
development:
  <<: *defaults
  database: paleospots_dev
staging:
  <<: *defaults
  database: paleospots_staging
test: &test
  <<: *defaults
  persist_in_safe_mode: false
  database: paleospots_test
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
